version: "3.5"

services:

    consignment:
        restart: always
        build: ./consignment-service
        image: shippy/consignment-service:1.1

        ports:
            - 50051:50051
        environment:
            MICRO_SERVER_ADDRESS: ":50051"
            DB_HOST: "192.168.10.194:3306"
            DB_NAME: "consignments"
            DB_USERNAME: "linac"
            DB_PASSWORD: "whut123"
        depends_on:
            - vessel

    vessel:
        restart: always
        build: ./vessel-service
        image: shippy/vessel-service:1.1
        ports:
            - 50052:50051
        environment:
            MICRO_SERVER_ADDRESS: ":50051"
            DB_HOST: "192.168.10.194:3306"
            DB_NAME: "consignments"
            DB_USERNAME: "linac"
            DB_PASSWORD: "whut123"